### ISSUE TITLE
Expand export modal functionality

### ISSUE THREAD

**Issue by heralden** [intermine/im-tables-3#101]
The export modal looks quite pitiful as of now.
![2020-08-11-110028_599x249_scrot](https://user-images.githubusercontent.com/3865590/89884849-04ddbb00-dbc2-11ea-8dcb-cf8a253bdbd0.png)

We should at least match the features of the original im-tables.
![2020-08-11-110113_900x404_scrot](https://user-images.githubusercontent.com/3865590/89884850-060ee800-dbc2-11ea-81ce-cfc5edbe4c21.png)

**Comment by heralden** [comment]
Suggestions from Gos:
- Show immediate response when downloading, e.g. "Please wait..." or close modal so user doesn't have to dismiss it themselves
- Use more informative filename instead of "results", e.g. "covidMine_results_21.02_20sep20_21.tsv"

**Comment by hendrikweisser** [comment]
Importantly, the TSV/CSV export currently doesn't include column headers. This can obviously lead to confusing results when there are multiple columns with similar content (e.g. numbers).
