### ISSUE TITLE
Save list needs more feedback

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables-3#11]
Upon successfully saving a list, it doesn’t give a message to say list created and a link to the list as current webapp does - I think this should be added. (via rachel)

I'm also not sure what happens if the list *doesn't* save successfully - does it fail silently?

**Comment by heralden** [comment]
The saved list alert has been added to BlueGenes (to use its alerting system) and I've added an event for failure as well (linked commit should appear soon). Just needs to be handled in bluegenes: https://github.com/intermine/bluegenes/issues/507
