### ISSUE TITLE
Convert Filter and Column Summary tooltips to modal

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables-3#18]
see https://github.com/intermine/im-tables-3/issues/15 - the tooltips are fiddly and sometimes hidden onscreen by other elements. modals will make their display and rendering much more straightforward and give them enough space....

**Comment by heralden** [comment]
Do we really want this, and is #15 still a problem? (Would love to see some screenshots of what you mean.)
Something to note about modals is that it makes it hard to reference the rest of the page as they'll be faded out.

**Comment by yochannah** [comment]
I can''t reproduce this right now so things may have changed. we can re-open if we need to.
