### ISSUE TITLE
Add columns blank dialogue

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables-3#25]
Steps to reproduce from @julie-sullivan 

>1. Organism --> All miRNA
>ran that template
>2. click on add column
>is blank
>on both live and dev

This could be one of the issues that only occurs in the embedded bluegenes, not the test app.

**Comment by heralden** [comment]
Seems like this is no longer an issue?

![2019-10-18-145900_1243x764_scrot](https://user-images.githubusercontent.com/3865590/67100588-dc5e7d80-f1b7-11e9-8a52-1942774845fa.png)
