### ISSUE TITLE
Remove pluralisation in model display

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables-3#26]
apparently we don't like manual client side pluralisation. 

https://github.com/intermine/im-tables-3/blob/812c5ff158821902d109d68a6d6455bce8111968/src/im_tables/views/dashboard/manager/columns/main.cljs#L34 I think that's it.

**Comment by yochannah** [comment]
compare old model view https://cdn.discordapp.com/attachments/258249422566064128/324151344766124034/model-currentmine.png

**Comment by joshkh** [comment]
@yochannah I'm now using the proper display names for all fields, however I'm keeping the pluralised collection names because we now have access to them via the JSON model.

![image](https://user-images.githubusercontent.com/4752532/28206674-ba870b06-687e-11e7-9d0a-e527a92966c9.png)

**Comment by yochannah** [comment]
@rachellyne @julie-sullivan I think one of you two reported this first. Does it look ok now?

**Comment by yochannah** [comment]
Rachel says it's ok. Yay.
