### ISSUE TITLE
Fix stacking of jQuery .on listeners

### ISSUE THREAD

**Issue by heralden** [intermine/im-tables-3#67]
In many places jQuery is used to define `.on` listeners in the element's `ref` attribute. This makes it possible for listeners to stack, causing the callback to be called multiple times per triggered event. We can fix this by always calling `.off` before `.on` to clear any existing listeners.

**Comment by yochannah** [comment]
do we actually need jquery at all, or could we migrate it to either jquery slim (excludes ajax and effects) or maybe plain 'ole clojurescript?

**Comment by heralden** [comment]
Bootstrap is pretty reliant on jquery (for like popovers and dropdowns) but we could try using the slimmed version if we're not already.

**Comment by yochannah** [comment]
oh, good point.
