### ISSUE TITLE
figure out how to export im-tables-3 css to bluegenes properly

### ISSUE THREAD

**Issue by yochannah** [intermine/im-tables-3#68]
right now we have to manually copy/paste styles. This is Not Good. I suspect there was a reason it was this way that we've forgotten, so it may not be an easy job.

**Comment by heralden** [comment]
Just a note: it should be possible to include the CSS files in the jar of the dependency, then have a process to copy them from the class path into bluegene's static resources.

A different solution would be to use [Garden](https://github.com/noprompt/garden).
